name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Initialize Repository
        uses: actions/checkout@v4

      - name: Initialize Docker
        uses: docker/setup-buildx-action@v2

      - name: Initialize Environment Variables
        run: cd docker && cat .env.template > .env

      - name: Build Docker Image
        run: cd docker && docker compose build --no-cache

      - name: Start Application
        run: cd docker && docker compose up -d

      - name: Stop Application
        run: cd docker && docker compose stop
